name: github CICD

on: [push, pull request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Run CI/CD
    -name: Run a multi -line script
      run: |
        echo add other action to build
        echo test, and deploy the project

